/*
 The PerDayRental class stores the details for a day rental vehicle
 
 @author David Pyle 041110777
 @version 1.0
 @since 11/4/2016
  
 Methods:
    + int getActualDaysRented()
    + void setActualDaysRented(int actualDaysRented)
    + double getDayRentalRevenue()
    + int getNumDays()
    + void setNumDays(int numDays)
    + double getNumKms()
    + void setNumKms(double numKms)
 */
package carrental;

/**
 *
 * @author 041110777
 */
public class PerDayRental {
    
    //number of days the vehicle is rented for
    private int numDays;
    //number of kilometres the vehicle is rented for
    private double numKms;
    //number of days the vehicle was actually rented for (may be different to inital days rented for)
    private int actualDaysRented;

    //rate of vehicle rental for 1 day ($100)
    private static final int RATE_PER_DAY = 100;
    
    /**
     * Constructor
     *
     * @param numKms the number of kilometres the rental is booked for
     * @param numDays the number of days the rental is booked for
     */
    public PerDayRental(double numKms, int numDays) {  
        
        this.numKms = numKms;
        this.numDays = numDays;
	this.actualDaysRented = 0;
    }

     /**
     * Gets the number of actual days the vehicle was rented for, this could be
     * different to the initial number of days the vehicle was rented for.
     *
     * @return the number of actual days the vehicle was rented
     */
     public int getActualDaysRented() {
         
	return actualDaysRented;
    }

     /**
     * Sets the number of actual days the vehicle was rented for, this could be
     * different to the initial number of days the vehicle was rented for.
     *
     * @param   actualDaysRented the number of actual days the vehicle was rented
     */
    public void setActualDaysRented(int actualDaysRented) {
        
	this.actualDaysRented = actualDaysRented;
    }
    
    /**
     * Gets the amount of revenue generated by the rental
     *
     * @return the amount of revenue for the rental
     */
    public double getDayRentalRevenue() {
        
        //return RATE_PER_DAY * numDays;
	return RATE_PER_DAY * actualDaysRented;
    }
    
    /**
     * Gets the number of days the vehicle was rented for, this value is determined
     * at the time of the rental booking and may change once the vehicle is returned.
     *
     * @return the number of days the vehicle was rented
     */
    public int getNumDays() {
        
        return numDays;
    }
    
    /**
     * Sets the number of days for the rental
     *
     * @param   numDays the number of days for the rental
     */
    public void setNumDays(int numDays) {
        
        this.numDays = numDays;
    }

    /**
     * Gets the number of kilometres travelled for the rental
     *
     * @return the number of kilometres for the rental
     */
    public double getNumKms() {
        
        return numKms;
    }
    
    /**
     * Sets the number of kilometres travelled for the rental
     *
     * @param   numKms the number of kilometres for the rental
     */
    public void setNumKms(double numKms) {
        
        this.numKms = numKms;
    }       
    
}
