/*
 The PerKmRental class stores the details for a per kilometre rental vehicle

 @author David Pyle 041110777
 @version 1.0
 @since 11/4/2016

 Methods:
    + double getActualKmForRental()
    + void setActualKmForRental(double actualKmForRental)
    + double getKmRentalRevenue()
    + double getNumKm()
    + void setNumKm(double numKm)
 */
package carrental;

public class PerKmRental {

    //num of kilometres for the rental booking
    private double numKm;
    //actual number of kilometres for the rental
    private double actualKmForRental;
    //rate per kilometre ($1 per km)
    private static final double RATE_PER_KM = 1;

    /**
     * Constructor
     *
     * @param numKm the number of kilometres the rental is booked for
     */
    public PerKmRental(double numKm) {

        //set default values
        this.numKm = numKm;
        this.actualKmForRental = 0;
    }

    /**
     * Gets the number of actual kilometres the vehicle was rented for, this
     * could be different to the initial number of kilometres the vehicle was
     * rented for.
     *
     * @return the number of actual number of kilometres the vehicle was rented
     */
    public double getActualKmForRental() {

        return actualKmForRental;
    }

    /**
     * Sets the number of actual kilometres the vehicle was rented for, this
     * could be different to the initial number of kilometres the vehicle was
     * rented for.
     *
     * @param actualKmForRental the number of actual number of kilometres the
     * vehicle travelled for the rental
     */
    public void setActualKmForRental(double actualKmForRental) {

        this.actualKmForRental += actualKmForRental;
    }

    /**
     * Gets the revenue generated by the rental
     *
     * @return the revenue for the rental
     */
    public double getKmRentalRevenue() {

        return RATE_PER_KM * actualKmForRental;
    }

    /**
     * Gets the number of kilometres the rental was booked for
     *
     * @return the number of kilometres the rental was booked for
     */
    public double getNumKm() {
        
        return numKm;
    }

    /**
     * Sets the number of kilometres the rental was booked for
     *
     * @param numKm the number of kilometres the rental was booked for
     */
    public void setNumKm(double numKm) {
        
        this.numKm = numKm;
    }

}
